name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  update:
    strategy:
      matrix:
        node-version: [20.x]

    name: Update all dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Update dependencies
        run: bunx npm-check-updates -u

      - name: Clean and reinstall
        run: |
          rm -rf node_modules bun.lockb
          bun install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "build: update dependencies to the latest version"
          title: Update dependencies to the latest version
